### ISSUE TITLE
Aerobee Tech Tree Suggestion

### ISSUE THREAD

**Issue by Skeltcher** [KSP-RO/USRockets#1]
Suggestion/Enhancement:

Change the tech required for the following to the "Start" tech node.
Aerobee 100 Fuel Tank
Aerobee 100/150/300 Solid Rocket Motor
Aerobee Sounding Rocket Motor
Aerobee 100/150/300 SRB Rocket Fin
Aerobee 100/150/170/300 Rocket Fin
*All of them currently at the "Basic Rocketry" tech node.

Change the tech required for the following to the "Survivability" tech node.
Aerobee 100/150/170 Payload Parachute
*Its currently at the "General Rocketry" tech node.

Change the tech required for the following to the "Basic Rocketry" tech node.
Aerobee 300 Nose Cone
Aerobee 300 Third Stage SRB Decoupler
Aerobee 350 Nose Cone
Aerboee 350 Probe Core
Aerobee 350 SRB Decoupler
*All of them currently at the "Start" tech node.

**Comment by raidernick** [comment]
make this a PR

**Comment by Skeltcher** [comment]
I tried but the option to create a new pull request is grayed for me.

**Comment by raidernick** [comment]
This is included in the latest release now: https://github.com/KSP-RO/USRockets/releases/tag/v0.5
